In [1]:
0.3 - 0.2 - 0.1

-2.7755575615628914e-17

In [3]:
import numpy as np
print(np.finfo(float).eps)

2.220446049250313e-16


In [8]:
np.pi

3.141592653589793

In [ ]:
print("Hello World")

Hello World


# **Numpy Introduction**

In [ ]:
import numpy as np

In [ ]:
a = 100  # scalar
type(a)

int

In [ ]:
id(a)

135009765330256

In [ ]:
b = [1, 2, 3]  # Python "list" of numbers
type(b)

list

In [ ]:
id(b)

135008494122560

In [ ]:
b

[1, 2, 3]

In [ ]:
# i want to multiply each number in b by 5
b * 5   # >>> the list got replicated 5 times

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
# i want to add 100 to each number in b
b + 100   # >>> eroor ... not possible

TypeError: ignored

In [ ]:
5**2  # 5 to the power of 2


25

In [ ]:
b**2  # i want to get the square of each number in b

TypeError: ignored

In [ ]:
arr = np.array(b)  # converting a Python list into a numpy array
type(arr)

numpy.ndarray

In [ ]:
arr

array([1, 2, 3])

In [ ]:
arr = np.array([1,2,3])
arr


array([1, 2, 3])

In [ ]:
arr.shape  # returns  the shape of the numpy array

(3,)

In [ ]:
arr.ndim # returns the number of dimensions of the numpy array

1

In [ ]:
arr + 100  # adding 100 to each number in the array

array([101, 102, 103])

In [ ]:
arr*5  # multiplying each number in the array by 5


array([ 5, 10, 15])

In [ ]:
arr**2  # squaring each number in the array


array([1, 4, 9])

In [ ]:
np.log(arr)  # natural log of each number in the array


array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.log10(arr)  # base 10 log of each number in the array

array([0.        , 0.30103   , 0.47712125])

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2.shape  # returns the shape of the numpy array
# 2 rows, 3 columns

(2, 3)

In [ ]:
arr2.ndim

2

In [ ]:
arr2 + 100  # sclaler addition to a matrix

array([[101, 102, 103],
       [104, 105, 106]])

In [ ]:
arr2*100  # scalar multiplication of a matrix

array([[100, 200, 300],
       [400, 500, 600]])

# Algebric Operations on MAtrices

In [ ]:
A = arr2
B = arr2*5
A.shape, B.shape

((2, 3), (2, 3))

In [ ]:
A, B

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 5, 10, 15],
        [20, 25, 30]]))

In [ ]:
# MAtrix Addition and Substraction are Element-wise operations.
# Hence, thier SHApES MUST BE exactly the same
A + B # matrix addition

array([[ 6, 12, 18],
       [24, 30, 36]])

In [ ]:
B.T  # transpose of B

array([[ 5, 20],
       [10, 25],
       [15, 30]])

In [ ]:
A + B.T

ValueError: ignored

In [ ]:
# Scaler multiplication to a vector/matrix goes element-wise (broadcasting)
10 * A

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
A*B  # element-wise multplication

array([[  5,  20,  45],
       [ 80, 125, 180]])

In [ ]:
A, B, B.T

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 5, 10, 15],
        [20, 25, 30]]),
 array([[ 5, 20],
        [10, 25],
        [15, 30]]))

In [ ]:
# For "proper" Matrix multiplication, we must ensure that the "inner dimensions" must match
np.matmul(A, B.T)

array([[ 70, 160],
       [160, 385]])

In [ ]:
# Matrix division IS NOT DEFINED
# Scaler division goes elelment-wise
A/10

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [ ]:
C = np.arange(1,10)   # start_no, stops 1 before the stop_no, default increment is 1
C  # 1D array of numbers

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
C = np.arange(0,80, 10)  # starts at 0, stops at 79, increment as 10
C

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [ ]:
C.size # number of elements in the numoy array  (no. of rows x no. columns)

8

In [ ]:
C.shape, C.ndim  # 1D array of numbers

((8,), 1)

In [ ]:
D = C.reshape(2,4)  # reshape the array into 2 rows and 4 columns
D

array([[ 0, 10, 20, 30],
       [40, 50, 60, 70]])

In [ ]:
col_vector = C.reshape(-1, 1)  # reshape the array into 8 rows and 1 column
col_vector

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50],
       [60],
       [70]])

In [ ]:
col_vector.ndim, col_vector.shape  # 2D array of numbers

(2, (8, 1))

In [ ]:
row_vector = C.reshape(1, -1)  # reshape the array into 1 ROW ONLY
row_vector

array([[ 0, 10, 20, 30, 40, 50, 60, 70]])

In [ ]:
row_vector[0,2]

20

In [ ]:
row_vector.shape

(1, 8)

In [ ]:
C.shape

(8,)

In [ ]:
C[2]

20

In [ ]:
A = np.arange(1,10).reshape(3,3)
A  # square matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A.diagonal()  # returns the diagonal elements of the matrix

array([1, 5, 9])

In [ ]:
np.fliplr(A)  # flips the matrix horizontally

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [ ]:
np.flipud(A)  # flips the matrix vertically

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
np.flipud(A).diagonal()  # returns the diagonal elements of the flipped matrix

array([7, 5, 3])

In [ ]:
A.trace()  # returns the sum of the MAIN diagonal elements of the matrix

15

In [ ]:
# np.flipud(A).diagonal().sum()
np.flipud(A).trace()

15

In [ ]:
v = [23, 45, 67, 33]
np.diag(v)  # creates a diagonal matrix from a vector

array([[23,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 67,  0],
       [ 0,  0,  0, 33]])

In [ ]:
np.linalg.det(A)  # returns the determinant of the matrix

0.0

In [ ]:
np.linalg.inv(A)

LinAlgError: ignored