# Matrix Operations

In [ ]:
import numpy as np

A = np.array([[1,   2,  3],
              [21, 35, 63],
              [17, 28, 39]])

print('The value of the determinant of A:', np.linalg.det(A))
A_inv = np.linalg.inv(A)
print("Inverse of A:\n", A_inv)

The value of the determinant of A: 84.00000000000006
Inverse of A:
 [[-4.75        0.07142857  0.25      ]
 [ 3.         -0.14285714  0.        ]
 [-0.08333333  0.07142857 -0.08333333]]


In [ ]:
# Singular matrices (whose det is ~0) are NOT Invertible
A1 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print('The value of the determinant of A1:', np.linalg.det(A1))
A1_inv = np.linalg.inv(A1)
A1_inv

The value of the determinant of A1: 0.0


LinAlgError: ignored

In [ ]:
I = np.eye(3) # Identity matrix of (3,3)
I.astype('int32')  # typecasting or Typeconversion

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [ ]:
I.dtype

dtype('float64')

In [ ]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ones = np.ones((4,4))*100
ones

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [ ]:
B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
np.matmul(A, B).T

array([[ 30, 602, 402],
       [ 36, 721, 486],
       [ 42, 840, 570]])

In [ ]:
np.matmul(B.T, A.T)

array([[ 30, 602, 402],
       [ 36, 721, 486],
       [ 42, 840, 570]])

# Rank of a Matrix
The rank of a matrix is a fundamental concept in linear algebra. It refers to the maximum number of linearly independent column vectors in the matrix or the maximum number of linearly independent row vectors in the matrix. Both definitions are equivalent.

**What Does Matrix Rank Mean?**

- **In terms of linear independence:** If you have a set of vectors, they are linearly independent if no vector in the set is a combination of other vectors. The rank of a matrix is the largest subset of rows or columns that is linearly independent. So, for a given matrix, if you have the maximum of 'r' rows (or columns) that are linearly independent, then no other set with more than 'r' rows (or columns) can be linearly independent, and thus the rank is 'r'.


**Applications of Matrix Rank:**

1. **Solving Systems of Linear Equations:** The rank is used to determine whether a system of linear equations has a unique solution, no solution, or infinitely many solutions.

2. **Economics and Business:** In input-output analysis, which examines the interdependencies between different industries, the rank of the matrix can reveal the chain of effects of one sector on others.

3. **Engineering and Computer Science:** In image processing, the rank of matrices representing digital images is studied for image compression. Lower-rank approximations can significantly compress the size of the image data.

4. **Data Science:** In machine learning, particularly in the reduction of dimensionality of data, techniques like Principal Component Analysis (PCA) work by computing a low-rank approximation of the data matrix.

5. **Psychometrics:** In factor analysis, used for assessing the validity of tests or questionnaires, the rank of a matrix determines the minimum number of common factors influencing a set of measures.

```

```

This code calculates and prints the rank of matrix A. The `matrix_rank` function uses the Singular Value Decomposition (SVD) method to calculate the rank accurately, including for matrices with zero or very small singular values.

In [1]:
import numpy as np

# # Creating a 2x3 matrix
A = np.array([[1,   2,  3],
              [21, 35, 63],
              [17, 28, 39]])

# Calculating the rank of the matrix
rank = np.linalg.matrix_rank(A)

print("Rank of the matrix:", rank)

Rank of the matrix: 3


In [2]:
# # Creating a 2x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [50, 70, 90]])

In [3]:
# A[2]= 3*A[0] - 5*A[1]   # 3rd row as linear combination of the 1st 2 rows
A[:,1] = 5*A[:,0]  # 2nd col as multiple of the 1st col
A[:,2] = 3*A[:,0] + 5*A[:,1] # 3rd col as linear combination of the 1st 2 cols

In [4]:
print(A)
# Calculating the rank of the matrix
rank = np.linalg.matrix_rank(A)

print("Rank of the matrix:", rank)

[[   1    5   28]
 [   4   20  112]
 [  50  250 1400]]
Rank of the matrix: 1


In [5]:
np.linalg.inv(A)

LinAlgError: Singular matrix

In [6]:
# # Creating a 2x3 matrix
A = np.array([[1, 2,  2],
              [4, 5, 20],
              [5, 7, 35]])

# Calculating the rank of the matrix
rank = np.linalg.matrix_rank(A)

print("Rank of the matrix:", rank)

Rank of the matrix: 3


# Solving System of Linear Equations

2x + 3y + 5z = 10

3x + 2y + 1z = 8

2x + 1y + 2z = 6


In [ ]:
import numpy as np

# Define your matrices
A = np.array([
    [2, 3, 5],
    [3, 2, 1],
    [2, 1, 2]
])
B = np.array([10, 8, 6])

# Check if A is a square matrix
if A.shape[0] == A.shape[1]:
    # Find the inverse of matrix A
    try:
        A_inv = np.linalg.inv(A)
    except np.linalg.LinAlgError:
        # Not invertible. Skip this one.
        print("Matrix A is singular and does not have an inverse.")
        A_inv = None

    if A_inv is not None:
        # Solve for x by multiplying the inverse of A with B
        x = np.dot(A_inv, B)

        # Print the solution
        print(f"Solutions:\nx: {x[0]}\ny: {x[1]}\nz: {x[2]}")
else:
    print("Matrix A is not square.")


Solutions:
x: 1.8181818181818181
y: 0.9090909090909087
z: 0.7272727272727275


In [7]:
# Coefficient matrix 'A' and constant matrix 'B'
A = np.array([[2, 3, 5],
              [3, 2, 1],
              [2, 1, 2]])
B = np.array([10, 8, 6])

# Solving the system of linear equations
x = np.linalg.solve(A, B)

# Print the solutions
print(f"Solutions:\nx: {x[0]}\ny: {x[1]}\nz: {x[2]}")


Solutions:
x: 1.8181818181818181
y: 0.9090909090909091
z: 0.7272727272727274


In [8]:
# finding roots of a Polynomial
import numpy as np

# x^2 - 7x + 6 = 0
coefficients = [1, -7, 6]
roots = np.roots(coefficients)
print(roots)

[6. 1.]
