# Vector Spaces

In mathematics, particularly in linear algebra, a **vector space** (or linear space) is a collection of vectors, which are objects that can be added together and multiplied ("scaled") by numbers, called scalars in this context. Scalars are often taken to be real numbers, but there are also vector spaces with scalar multiplication by complex numbers, rational numbers, or generally any field.

The key characteristics of a vector space include two operations: vector addition and scalar multiplication. For a set to be considered a vector space, it must satisfy the following conditions:
- **Associativity of addition**: $ \mathbf{u} + (\mathbf{v} + \mathbf{w}) = (\mathbf{u} + \mathbf{v}) + \mathbf{w} $
- **Commutativity of addition**: $ \mathbf{u} + \mathbf{v} = \mathbf{v} + \mathbf{u} $
- **Identity element of addition**: There exists an element $ \mathbf{0} $ such that $ \mathbf{u} + \mathbf{0} = \mathbf{u} $ for any $ \mathbf{u} $
- **Inverse elements of addition**: For every $ \mathbf{u} $, there exists an element $ -\mathbf{u} $ such that $ \mathbf{u} + (-\mathbf{u}) = \mathbf{0} $
- **Compatibility of scalar multiplication with field multiplication**: $ a(b\mathbf{u}) = (ab)\mathbf{u} $
- **Identity element of scalar multiplication**: $ 1\mathbf{u} = \mathbf{u} $
- **Distributivity of scalar multiplication with respect to vector addition**: $ a(\mathbf{u} + \mathbf{v}) = a\mathbf{u} + a\mathbf{v} $
- **Distributivity of scalar multiplication with respect to field addition**: $ (a + b)\mathbf{u} = a\mathbf{u} + b\mathbf{u} $

### Where Vector Spaces are Used in Data Science

**1. Machine Learning Algorithms**
- **Feature Spaces**: In machine learning, especially in supervised learning, each data point is often represented as a vector within a feature space. This vector space is critical for various algorithms such as support vector machines (SVMs), where data points are manipulated in high-dimensional vector spaces to determine decision boundaries.
- **Model Parameter Space**: Many models in machine learning, including neural networks, operate in a parameter space that is essentially a vector space. Optimization techniques such as gradient descent navigate this space to find the optimal parameters that minimize a loss function.

**2. Natural Language Processing (NLP)**
- **Word Embeddings**: Tools like Word2Vec or GloVe represent words in a high-dimensional vector space where the vector operations have semantic meanings. For example, the analogy "king is to queen as man is to woman" can be represented by vector equations.
- **Document Vectors**: Techniques like Latent Semantic Analysis (LSA) use vector spaces to reduce the dimensionality of the text data, helping in summarization, topic modeling, and similarity detection.

**3. Computer Vision**
- **Image Representations**: Images are often represented as vectors (or tensors) in a vector space. Operations in this space can be used for image recognition, transformation, and other image processing tasks.

**4. Recommender Systems**
- **Collaborative Filtering**: Methods like matrix factorization represent users and items as vectors in a low-dimensional latent space. The interactions between user and item vectors are used to predict missing entries (e.g., user ratings), which can recommend new items to users.

**5. Data Visualization**
- **Dimensionality Reduction**: Techniques like PCA and t-SNE involve transformations within vector spaces to project high-dimensional data into lower dimensions for visualization while preserving certain relationships or structures from the original space.

### Python Example

In [3]:
import numpy as np

# Define vectors
u = np.array([1, 2, 3, 4])
v = np.array([-1, 0, 1, 3])
w = np.array([4, 5, 6, -2])

In [4]:
# Vector addition
addition = u + v
addition

array([0, 2, 4, 7])

In [5]:
# Scalar multiplication
scalar_multiplication = 3 * u
scalar_multiplication

array([ 3,  6,  9, 12])

In [7]:
# Linear combination
linear_combination = 2*u - 3*v + 4*w
linear_combination

array([21, 24, 27, -9])

# Vector Subspaces

In linear algebra, a **vector subspace** is a subset of a vector space that itself is a vector space under the operations of vector addition and scalar multiplication defined on the larger vector space. For a subset $ W $ of a vector space $ V $ to be considered a subspace, it must satisfy three conditions:
1. **Non-emptiness/Contains the Zero Vector**: $ W $ must include the zero vector of $ V $.
2. **Closed under Addition**: For any vectors $ u $ and $ v $ in $ W $, the sum $ u + v $ must also be in $ W $.
3. **Closed under Scalar Multiplication**: For any vector $ u $ in $ W $ and any scalar $ c $, the product $ c \cdot u $ must also be in $ W $.

These properties ensure that any linear combination of vectors in $ W $ also belongs to $ W $, thereby making $ W $ a vector space in its own right.

### Applications of Vector Subspaces in Data Science

Vector subspaces are fundamental in many aspects of data science and related fields such as machine learning, statistics, and computer science. Here are some key areas where vector subspaces are particularly relevant:

**1. Machine Learning**
- **Feature Spaces**: In machine learning, especially in methods like PCA or LDA (Linear Discriminant Analysis), the feature space is often reduced to a subspace that captures the most variance or best separates classes. These reduced spaces are subspaces of the original feature space.
- **Regularization and Constraint**: Techniques like ridge regression or Lasso involve constraining or regularizing parameters to lie within a certain subspace, often defined by norm constraints.

**2. Natural Language Processing (NLP)**
- **Semantic and Syntactic Subspaces**: In NLP, different vector subspaces within word embedding spaces may capture semantic or syntactic relationships between words. Operations within these subspaces can reveal linguistic patterns and relationships.
- **Topic Modeling**: Methods like LSA decompose text data into subspaces that capture thematic structures, where each subspace may correspond to a topic.

**3. Computer Vision**
- **Image Transformations and Filters**: In image processing, certain transformations can be considered as mapping images into subspaces that emphasize specific features or properties, such as edges or frequencies. Fourier transforms and wavelet transforms create subspaces that isolate specific characteristics of images.

**4. Data Visualization**
- **Dimensionality Reduction**: Visualization techniques often involve projecting high-dimensional data into lower-dimensional subspaces (using methods like t-SNE or PCA) to make the data visually comprehensible while preserving certain statistical properties or structures.

**5. Recommender Systems**
- **Latent Factor Models**: In these systems, user preferences and item characteristics are often modeled in lower-dimensional subspaces, where dimensions correspond to latent factors (possibly representing genres, themes, etc.). This subspace framework helps in predicting user-item interactions effectively.

### Python Example: Checking for a Subspace

In [8]:
import numpy as np

# Define vectors in R^3
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])

# Check if their sum is in the span of v1 and v2
v_sum = v1 + v2
v_sum

array([1, 1, 0])

In [9]:
# Check if a scalar multiple is in the span
v_scalar = 3*v1 - 2*v2
v_scalar

array([ 3, -2,  0])

# MAtrix Spaces

## 1. Row Space

**Definition:**
The row space of a matrix $ A $, also known as the row space of $ A $, consists of all possible linear combinations of the row vectors of the matrix. It is a subspace of $ \mathbb{R}^n $ if $ A $ is an $ m \times n $ matrix.

**Mathematical Representation:**
If $ A $ is represented as:
$$
A = \begin{bmatrix}
\mathbf{r}_1 \\
\mathbf{r}_2 \\
\vdots \\
\mathbf{r}_m
\end{bmatrix}
$$
where each $ \mathbf{r}_i $ is a row vector, the row space can be expressed as the span of these row vectors:
$$
\text{Row Space}(A) = \text{Span}(\mathbf{r}_1, \mathbf{r}_2, ..., \mathbf{r}_m)
$$

**Importance:**
The dimension of the row space is called the rank of the matrix. The rank reveals how many linearly independent row vectors exist in the matrix, which is crucial for understanding the solution set of the corresponding system of linear equations.

## 2. Column Space

**Definition:**
The column space of a matrix $ A $, also known as the range of $ A $, is the set of all possible linear combinations of the column vectors of the matrix. This space represents all the vectors that can be obtained by multiplying $ A $ with some vector $ \mathbf{x} $.

**Mathematical Representation:**
If $ A $ is an $ m \times n $ matrix with columns $ \mathbf{c}_1, \mathbf{c}_2, ..., \mathbf{c}_n $, then the column space is given by:
$$
\text{Col Space}(A) = \text{Span}(\mathbf{c}_1, \mathbf{c}_2, ..., \mathbf{c}_n)
$$

**Importance:**
The column space is critical in determining the output of $ A\mathbf{x} $ for any $ \mathbf{x} $. It also helps in solving linear equations, particularly in understanding whether a system of equations $ A\mathbf{x} = \mathbf{b} $ has a solution. If $ \mathbf{b} $ is in the column space of $ A $, then the system is solvable.

## 3. Null Space

**Definition:**
The null space (or kernel) of a matrix $ A $ consists of all vectors $ \mathbf{x} $ such that $ A\mathbf{x} = \mathbf{0} $. It contains all solutions to the homogeneous equation $ A\mathbf{x} = \mathbf{0} $ and represents the set of vectors that are mapped to the zero vector by $ A $.

**Mathematical Representation:**
If $ A $ is an $ m \times n $ matrix, then the null space is defined as:
$$
\text{Null Space}(A) = \{\mathbf{x} \in \mathbb{R}^n : A\mathbf{x} = \mathbf{0}\}
$$

**Importance:**
The null space is fundamental in solving systems of linear equations, particularly in finding the general solution to the system. The dimension of the null space, called the nullity of $ A $, along with the rank of $ A $, satisfies the Rank-Nullity Theorem: $\text{rank}(A) + \text{nullity}(A) = n$, where $ n $ is the number of columns of $ A $.

### Applications Across Fields

- **Systems of Linear Equations**: Understanding these spaces helps in solving both homogeneous and non-homogeneous systems.
- **Engineering and Physics**: These concepts are used in mechanics, electronics, and quantum mechanics for various analytical solutions.
- **Data Science**: They are crucial in Principal Component Analysis (PCA) for dimensionality reduction, regression analysis, and more sophisticated machine learning algorithms that require an understanding of the underlying data structure.

In [10]:
# Define a 3x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Matrix A:")
print(A)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
import numpy as np
from scipy.linalg import null_space

# Finding the null space using SciPy
nullspace = null_space(A)
print("\nNull space:")
print(nullspace)


Null space:
[[-0.40824829]
 [ 0.81649658]
 [-0.40824829]]
