# LU decomposition and QR factorization
LU decomposition and QR factorization are common techniques in linear algebra for solving linear equations, inverting matrices, and computing determinants efficiently. Below are examples of how to perform these decompositions in Python using the NumPy and SciPy libraries.

LU Decomposition is typically more complex, and for practical purposes, using a library is recommended. Here’s a brief outline of the algorithm, but note that implementing this correctly and efficiently from scratch is non-trivial:

- **Initialize $ L $ and $ U $**: Start with $ L $ as the identity matrix and $ U $ as a copy of $ A $.
- **Gaussian Elimination Process**: For each element below the diagonal in $ U $ (i.e., $ U_{ij} $ where $ i > j $), calculate the factor $ L_{ij} = U_{ij} / U_{jj} $ and store it in $ L $. Use $ L_{ij} $ to subtract the appropriate multiple of row $ j $ from row $ i $ in $ U $, setting $ U_{ij} $ to zero, which effectively performs the elimination process.

## 1. LU Decomposition

**Definition:**
LU decomposition factors a matrix $A$ into the product of a lower triangular matrix $L$ and an upper triangular matrix $U$.

$$ A = LU $$

- **L** is a lower triangular matrix with unit diagonal elements (in some definitions, the diagonal elements can be arbitrary).
- **U** is an upper triangular matrix.

**Purpose:**
LU decomposition is used for solving linear systems, computing determinants, and inverting matrices.

**Characteristics:**
- Generally applied to square matrices ($n \times n$).
- May require row permutations (pivoting) to ensure numerical stability, leading to $PA = LU$ where $P$ is a permutation matrix.

**Applications:**
- Efficiently solving multiple linear systems with the same coefficient matrix.
- Matrix inversion.
- Computing determinants: $\det(A) = \det(L) \cdot \det(U)$.

LU Decomposition factors a matrix as the product of a lower triangular matrix and an upper triangular matrix (along with a permutation matrix). Here's how you can do this in Python using the `scipy.linalg.lu` function.

In the case below, `A` is the matrix you want to decompose, and `P`, `L`, and `U` are the permutation, lower triangular, and upper triangular matrices, respectively.

In [2]:
import numpy as np
from scipy.linalg import lu

# Define a square matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 10]
])

# Perform LU decomposition
P, L, U = lu(A)

print("Original Matrix:")
print(A)
print("\nP = ")
print(P)
print("\nL = ")
print(L)
print("\nU = ")
print(U)


Original Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

P = 
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

L = 
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]

U = 
[[ 7.          8.         10.        ]
 [ 0.          0.85714286  1.57142857]
 [ 0.          0.         -0.5       ]]


## Reconstruction
Once you have the matrices $ P $, $ L $, and $ U $ from an LU decomposition, reconstructing the original matrix $ A $ involves a simple matrix multiplication of these components. However, it's important to remember that $ P $ is a permutation matrix, which represents row interchanges made during the LU decomposition for numerical stability.

To reconstruct the matrix $ A $ from its LU decomposition components, you multiply $ P $, $ L $, and $ U $ in that specific order: $ A = P \times L \times U $.

Here’s how you can do this in Python using the NumPy library, assuming you have already decomposed $ A $ into $ P $, $ L $, and $ U $ using the SciPy library:

### Step-by-Step Code to Reconstruct $ A $ from $ P $, $ L $, and $ U $

**Reconstruct $ A $ Using Matrix Multiplication**

Use NumPy's `dot` function to multiply $ P $, $ L $, and $ U $ in the correct order.

In [4]:
A_reconstructed = np.dot(P, np.dot(L, U))
A_reconstructed

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8., 10.]])

## 2. QR Factorization


**Definition:**
QR-factorization decomposes a matrix $A$ into a product of an orthogonal matrix $Q$ and an upper triangular matrix $R$.

$$ A = QR $$

- **Q** is an orthogonal matrix (or unitary if $A$ is complex), meaning $Q^T Q = I$.
- **R** is an upper triangular matrix.

**Purpose:**
QR-factorization is primarily used for solving linear systems, least squares problems, and for computing eigenvalues. 

**Characteristics:**
- Applicable to any $m \times n$ matrix.
- Preserves orthogonality.
- Often used in iterative algorithms, such as the QR algorithm for finding eigenvalues.

**Applications:**
- Solving linear systems: $Ax = b \rightarrow QRx = b$
- Least squares problems: Minimizing $\|Ax - b\|$ for overdetermined systems.

QR factorization decomposes a matrix into a product of an orthogonal matrix and an upper triangular matrix. Here's how you can perform QR factorization using NumPy with the `numpy.linalg.qr` function.

In the code below, `A` is the matrix you want to factorize, and `Q` and `R` are the orthogonal and upper triangular matrices, respectively.

In [ ]:
import numpy as np

# Define a matrix
A = np.array([
    [12, -51, 4],
    [6, 167, -68],
    [-4, 24, -41]
])

# Perform QR factorization
Q, R = np.linalg.qr(A)

print("Original Matrix:")
print(A)
print("\nQ = ")
print(Q)
print("\nR = ")
print(R)

Original Matrix:
[[ 12 -51   4]
 [  6 167 -68]
 [ -4  24 -41]]

Q = 
[[-0.85714286  0.39428571  0.33142857]
 [-0.42857143 -0.90285714 -0.03428571]
 [ 0.28571429 -0.17142857  0.94285714]]

R = 
[[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


## Applications of QR Factorization
- Solving Linear Systems: QR factorization is particularly useful for solving linear systems that are overdetermined (more equations than unknowns) or when the matrix is square but poorly conditioned.

- Least Squares Regression: In statistics and machine learning, QR factorization is used to solve least squares problems efficiently, which is crucial for linear regression models.

- Eigenvalue Computations: In numerical algorithms, QR factorization is a common method for finding the eigenvalues of a matrix, especially when combined with shift strategies.

# MAtrix Inverse using LU Decomposition

LU decomposition can be utilized to calculate the inverse of a matrix \( A \) efficiently. The basic idea is to use the LU decomposition of \( A \) to solve the system \( AX = I \) for \( X \), where \( I \) is the identity matrix, and \( X \) will be the inverse of \( A \).

Here's a step-by-step breakdown:

1. Decompose the matrix \( A \) into its LU components: \( A = LU \).
2. For each column \( i \) of the identity matrix \( I \):
    - a. Solve the lower triangular system \( LY = I[:,i] \) for \( Y \).
    - b. Solve the upper triangular system \( UX = Y \) for \( X \).
    - c. The resulting \( X \) is the \( i^{th} \) column of \( A^{-1} \).

Remember, not all matrices have an inverse. If \( A \) is singular, then this process won't provide a meaningful result.

In [ ]:
import numpy as np
from scipy.linalg import lu_factor, lu_solve

def matrix_inverse_using_lu(A):
    # Retrieve the number of rows (or columns) for the square matrix A
    n = A.shape[0]

    # Perform LU decomposition on the input matrix A.
    # 'lu' is the combined form of lower and upper triangular matrices.
    # 'piv' holds the pivot indices showing row swaps made during the decomposition process.
    lu, piv = lu_factor(A)

    # Create an identity matrix of size 'n x n'. This matrix serves as the right-hand side
    # of the equation system to be solved for finding the inverse. Each column in the identity
    # matrix is used in turn to solve the equation system.
    I = np.eye(n)

    # Initialize an empty matrix of zeros with the same shape as A to store the inverse.
    # The data type is specified as float64 for higher precision.
    invA = np.zeros_like(A, dtype=np.float64)

    # Iterate over each column of the identity matrix.
    for i in range(n):
        # For each column, solve the equation system 'Ax = I[:, i]' where 'A' is the original
        # matrix, 'x' is the column vector of the inverse we are solving for, and 'I[:, i]'
        # is the current column of the identity matrix.
        # The function 'lu_solve' is used with the LU decomposition results and the current
        # column of the identity matrix to find each 'x' (each column of the inverse matrix).
        invA[:, i] = lu_solve((lu, piv), I[:, i])

    # After finding all columns of the inverse matrix, return the completed inverse.
    return invA

# Define a matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 10]
], dtype=np.float64)  # Ensure the dtype is float for precision

# Calculate the inverse using LU decomposition
A_inv_lu = matrix_inverse_using_lu(A)

# Using NumPy's built-in function to find the inverse
A_inv_np = np.linalg.inv(A)

# Print the results
print("Inverse using LU decomposition:")
print(A_inv_lu)
print("\nInverse using NumPy:")
print(A_inv_np)

# Verify if the results are approximately equal
if np.allclose(A_inv_lu, A_inv_np):
    print("\nBoth methods give approximately the same result.")
else:
    print("\nResults are different.")

# Validation by checking A_inv * A = I
print("\nValidation by multiplying the original matrix by its inverse:")
result = np.dot(A, A_inv_lu)
print(result)

# Check if the result is close to the identity matrix
identity_matrix = np.eye(A.shape[0])
if np.allclose(result, identity_matrix):
    print("\nThe result is approximately an identity matrix. The minor discrepancies are due to floating-point precision.")
else:
    print("\nThe result significantly deviates from an identity matrix. There may be an issue with the calculations.")

Inverse using LU decomposition:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]

Inverse using NumPy:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]

Both methods give approximately the same result.

Validation by multiplying the original matrix by its inverse:
[[1.00000000e+00 0.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00 2.22044605e-16]
 [8.88178420e-16 0.00000000e+00 1.00000000e+00]]

The result is approximately an identity matrix. The minor discrepancies are due to floating-point precision.


In [ ]:
import scipy.linalg as la
import numpy as np

def inverse_via_lu(A):
    # Step 1: Perform LU Decomposition
    P, L, U = la.lu(A)

    # Step 2: Solve for the inverse
    n = A.shape[0]
    I = np.eye(n)
    A_inv = np.zeros_like(A)

    for i in range(n):
        b = I[:, i]  # This selects the i-th column of the Identity matrix
        y = la.solve_triangular(L, np.dot(P.T, b), lower=True)  # Solve Ly = Pb for y
        x = la.solve_triangular(U, y, lower=False)  # Now solve Ux = y for x
        A_inv[:, i] = x  # Place the solution in the appropriate column

    return A_inv

# Define a matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 10]
], dtype=np.float64)  # Ensure the dtype is float for precision

A_inv = inverse_via_lu(A)

print("Original Matrix:")
print(A)

print("\nInverse Matrix:")
print(A_inv)

# Verification: multiplying a matrix by its inverse should yield the identity matrix
print("\nA * A_inv:")
print(np.dot(A, A_inv))


Original Matrix:
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. 10.]]

Inverse Matrix:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]

A * A_inv:
[[1.00000000e+00 0.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00 2.22044605e-16]
 [8.88178420e-16 0.00000000e+00 1.00000000e+00]]


This function first decomposes the matrix `A` into `P`, `L`, and `U` matrices (permutation, lower, and upper triangular matrices, respectively). It then solves the system of equations Ly = Pb and Ux = y for each column of the identity matrix, effectively solving the equation Ax = I, where `I` is the identity matrix. The solutions `x` are the columns of the inverse matrix.

# Summary of Differences between LU, QR & SVD

1. **Matrix Types:**
   - QR: Applicable to any $m \times n$ matrix.
   - LU: Typically applied to square matrices ($n \times n$).
   - SVD: Applicable to any $m \times n$ matrix.

2. **Components:**
   - QR: Orthogonal matrix $Q$ and upper triangular matrix $R$.
   - LU: Lower triangular matrix $L$ and upper triangular matrix $U$.
   - SVD: Orthogonal matrices $U$ and $V$, and diagonal matrix $\Sigma$.

3. **Orthogonality:**
   - QR and SVD involve orthogonal (or unitary) matrices.
   - LU does not involve orthogonal matrices.

4. **Applications:**
   - QR: Solving linear systems, eigenvalue computation, least squares.
   - LU: Solving linear systems, matrix inversion, computing determinants.
   - SVD: Low-rank approximations, pseudoinverses, PCA, data compression.

5. **Numerical Stability:**
   - QR and SVD are generally more numerically stable compared to LU, especially without pivoting.
